"""Milimo Quantum — Academic Citation & Metadata Export.

Generate BibTeX citations for quantum algorithms and structured metadata 
for research reproducibility.
"""
from __future__ import annotations

from datetime import datetime
from app.auth import get_current_user
from fastapi import APIRouter, Depends

router = APIRouter(prefix="/api/citations", tags=["citations"], dependencies=[Depends(get_current_user)])

# Common algorithm citations (simulated database)
ALGO_CITATIONS = {
    "vqe": """@article{peruzzo2014variational,
  title={A variational eigenvalue solver on a photonic quantum processor},
  author={Peruzzo, Alberto and McClean, Jarrod and Shadbolt, Peter and Yung, Man-Hong and Zhou, Xiao-Qi and Love, Peter J and Aspuru-Guzik, Alán and O'Brien, Jeremy L},
  journal={Nature communications},
  volume={5},
  number={1},
  pages={4213},
  year={2014},
  publisher={Nature Publishing Group}
}""",
    "qaoa": """@article{farhi2014quantum,
  title={A quantum approximate optimization algorithm},
  author={Farhi, Edward and Goldstone, Jeffrey and Gutmann, Sam},
  journal={arXiv preprint arXiv:1411.4028},
  year={2014}
}""",
    "shor": """@inproceedings{shor1994algorithms,
  title={Algorithms for quantum computation: discrete logarithms and factoring},
  author={Shor, Peter W},
  booktitle={Proceedings 35th annual symposium on foundations of computer science},
  pages={124--134},
  year={1994},
  organization={Ieee}
}""",
    "grover": """@inproceedings{grover1996fast,
  title={A fast quantum mechanical algorithm for database search},
  author={Grover, Lov K},
  booktitle={Proceedings of the twenty-eighth annual ACM symposium on Theory of computing},
  pages={212--219},
  year={1996}
}""",
    "qiskit": """@misc{Qiskit,
    author = {{Qiskit contributors}},
    title = {Qiskit: An Open-source Framework for Quantum Computing},
    year = {2023},
    doi = {10.5281/zenodo.2573505}
}"""
}


@router.get("/bibtex/{conversation_id}")
async def get_bibtex(conversation_id: str):
    """Generate BibTeX citations for a conversation."""
    # In a real app, we would parse the conversation for algorithm keywords.
    # Here we mock it by returning a standard set plus Qiskit.
    
    citations = [ALGO_CITATIONS["qiskit"]]
    
    # Mock detection logic
    # if "vqe" in conversation_content: citations.append(ALGO_CITATIONS["vqe"])
    
    return {"bibtex": "\n\n".join(citations)}


@router.get("/metadata/{conversation_id}")
async def get_reproducibility_metadata(conversation_id: str):
    """Generate structured JSON-LD metadata for experiment reproducibility."""
    from app.quantum.hal import hal_config
    
    return {
        "@context": "https://schema.org",
        "@type": "Dataset",
        "name": f"Quantum Experiment - {conversation_id}",
        "description": "Quantum circuit execution results generated by Milimo Quantum",
        "creator": {
            "@type": "SoftwareApplication",
            "name": "Milimo Quantum",
            "version": "0.1.0"
        },
        "dateCreated": datetime.now().isoformat(),
        "variableMeasured": ["Counts", "Quasi-Probabilities"],
        "softwareVersion": {
            "qiskit": "2.2.0",
            "python": "3.12"
        },
        "hardware": {
            "backend": hal_config.aer_device, # e.g. "CPU" or "GPU"
            "platform": hal_config.os_name
        }
    }
